export const mockEvents = [
  {
    id: "jazz-1",
    name: "Joe Lovano Quartet",
    artist: "Joe Lovano Quartet",
    venue: "Village Vanguard",
    city: "Greenwich Village",
    date: "2025-01-31",
    time: "Evening sets",
    genre: "Jazz",
    image: "/jazz-quartet-village-vanguard.jpg",
    price: { min: 45, max: 45 },
    attendance: { projected: 120, capacity: 150 },
    demand: 95,
  },
  {
    id: "jazz-2",
    name: "Rising Voices Jazz Night",
    artist: "Rising Voices Jazz Night",
    venue: "Smalls Jazz Club",
    city: "West Village",
    date: "2025-02-01",
    time: "9:30 PM",
    genre: "Jazz",
    image: "/jazz-club-intimate-performance.jpg",
    price: { min: 30, max: 30 },
    attendance: { projected: 80, capacity: 100 },
    demand: 88,
  },
  {
    id: "jazz-3",
    name: "Modern Jazz Collective",
    artist: "Modern Jazz Collective",
    venue: "Blue Note Jazz Club",
    city: "Midtown",
    date: "2025-02-01",
    time: "8:00 PM",
    genre: "Jazz",
    image: "/modern-jazz-blue-note-club.jpg",
    price: { min: 55, max: 55 },
    attendance: { projected: 180, capacity: 200 },
    demand: 92,
  },
  //
  {
    id: "1",
    name: "Neon Dreams Tour",
    artist: "Luna Eclipse",
    venue: "The Anthem",
    city: "Washington DC",
    date: "2025-01-15",
    time: "8:00 PM",
    genre: "Electronic",
    image: "/electronic-concert-neon-lights.jpg",
    price: { min: 45, max: 120 },
    attendance: { projected: 2800, capacity: 3500 },
    demand: 87,
  },
  {
    id: "2",
    name: "Acoustic Sessions",
    artist: "River Stone",
    venue: "Blue Note",
    city: "New York",
    date: "2025-01-18",
    time: "9:00 PM",
    genre: "Jazz",
    image: "/jazz-club-intimate-performance.jpg",
    price: { min: 35, max: 85 },
    attendance: { projected: 180, capacity: 200 },
    demand: 94,
  },
  {
    id: "3",
    name: "Summer Vibes Festival",
    artist: "Multiple Artists",
    venue: "Pier 17",
    city: "New York",
    date: "2025-01-22",
    time: "4:00 PM",
    genre: "Indie Pop",
    image: "/outdoor-music-festival-summer.jpg",
    price: { min: 75, max: 200 },
    attendance: { projected: 4200, capacity: 5000 },
    demand: 78,
  },
  {
    id: "4",
    name: "Underground Beats",
    artist: "DJ Phantom",
    venue: "Warehouse 9",
    city: "Los Angeles",
    date: "2025-01-25",
    time: "11:00 PM",
    genre: "Techno",
    image: "/underground-techno-club-dark.jpg",
    price: { min: 30, max: 60 },
    attendance: { projected: 850, capacity: 1000 },
    demand: 82,
  },
  // Demo conviction events
  {
    id: "neon-dreams-demo",
    name: "Neon Dreams",
    artist: "Neon Dreams",
    venue: "The Atlas Room",
    city: "Brooklyn, NY",
    date: "2026-02-25",
    time: "8:30 PM",
    genre: "Electronic",
    image: "/electronic-concert-neon-lights.jpg",
    price: { min: 32, max: 38 },
    attendance: { projected: 210, capacity: 250 },
    demand: 87,
  },
  {
    id: "acoustic-sessions-demo",
    name: "Acoustic Sessions",
    artist: "Willow & The Waves",
    venue: "Harmony Hall",
    city: "Manhattan, NY",
    date: "2026-02-25",
    time: "9:00 PM",
    genre: "Folk",
    image: "/acoustic-folk-performance-intimate-venue.jpg",
    price: { min: 22, max: 28 },
    attendance: { projected: 195, capacity: 240 },
    demand: 82,
  },
  {
    id: "lunar-bloom-demo",
    name: "Lunar Bloom",
    artist: "Lunar Bloom",
    venue: "Warehouse 9",
    city: "Brooklyn, NY",
    date: "2026-02-27",
    time: "10:00 PM",
    genre: "Electronic",
    image: "/neon-club-electronic-music-night.jpg",
    price: { min: 28, max: 35 },
    attendance: { projected: 320, capacity: 450 },
    demand: 74,
  },
  {
    id: "static-youth-demo",
    name: "Static Youth",
    artist: "Static Youth",
    venue: "The Lot Radio",
    city: "Brooklyn, NY",
    date: "2026-02-26",
    time: "7:30 PM",
    genre: "Indie",
    image: "/indie-rock-showcase-small-venue.jpg",
    price: { min: 18, max: 22 },
    attendance: { projected: 85, capacity: 120 },
    demand: 69,
  },
  {
    id: "summer-vibes-demo",
    name: "Summer Vibes Festival",
    artist: "Various Artists",
    venue: "Prospect Park Bandshell",
    city: "Brooklyn, NY",
    date: "2026-06-14",
    time: "2:00 PM",
    genre: "Multi-Genre",
    image: "/outdoor-festival-sunset-crowd.jpg",
    price: { min: 55, max: 120 },
    attendance: { projected: 2400, capacity: 5000 },
    demand: 79,
  },
  {
    id: "velvet-echo-demo",
    name: "Velvet Echo",
    artist: "Velvet Echo",
    venue: "Le Poisson Rouge",
    city: "Manhattan, NY",
    date: "2026-03-07",
    time: "9:30 PM",
    genre: "Synth-Pop",
    image: "/concert-poster-artwork-neon.jpg",
    price: { min: 25, max: 30 },
    attendance: { projected: 150, capacity: 250 },
    demand: 68,
  },
]

export const mockArtists = [
  {
    id: "1",
    name: "Luna Eclipse",
    genre: "Electronic",
    followers: 125000,
    monthlyListeners: 890000,
    image: "/female-electronic-music-dj-artist-with-neon-lights.jpg",
    popularity: 87,
    location: "Los Angeles, CA",
    badge: "Trending",
    bio: "Boundary-pushing electronic artist known for immersive live shows.",
    socialLinks: {
      instagram: "https://instagram.com/lunaeclipse",
      spotify: "https://open.spotify.com/artist/lunaeclipse",
      youtube: "https://youtube.com/@lunaeclipse",
      tiktok: "https://tiktok.com/@lunaeclipse",
      indieCity: "https://indiecity.com/lunaeclipse",
      website: "https://lunaeclipse.com",
    },
  },
  {
    id: "2",
    name: "River Stone",
    genre: "Jazz",
    followers: 45000,
    monthlyListeners: 320000,
    image: "/jazz-musician-portrait-with-saxophone-dark-moody.jpg",
    popularity: 72,
    location: "New York, NY",
    badge: null,
    bio: "Contemporary jazz virtuoso blending traditional techniques with modern improvisation.",
    socialLinks: {
      instagram: "https://instagram.com/riverstone",
      spotify: "https://open.spotify.com/artist/riverstone",
      youtube: null,
      tiktok: null,
      indieCity: "https://indiecity.com/riverstone",
      website: "https://riverstone.music",
    },
  },
  {
    id: "3",
    name: "The Velvet Underground Revival",
    genre: "Rock",
    followers: 78000,
    monthlyListeners: 540000,
    image: "/rock-band-group-photo-vintage-aesthetic-four-membe.jpg",
    popularity: 79,
    location: "Brooklyn, NY",
    badge: "Local to you",
    bio: "Modern rock collective channeling the experimental spirit of the 60s NYC scene.",
    socialLinks: {
      instagram: "https://instagram.com/velvetrevival",
      spotify: "https://open.spotify.com/artist/velvetrevival",
      youtube: "https://youtube.com/@velvetrevival",
      tiktok: "https://tiktok.com/@velvetrevival",
      indieCity: null,
      website: null,
    },
  },
  {
    id: "4",
    name: "DJ Phantom",
    genre: "Techno",
    followers: 92000,
    monthlyListeners: 670000,
    image: "/techno-dj-at-club-booth-with-dramatic-lighting-dar.jpg",
    popularity: 85,
    location: "Berlin, Germany",
    badge: "Trending",
    bio: "Underground techno producer bringing dark, hypnotic beats to warehouse raves worldwide.",
    socialLinks: {
      instagram: "https://instagram.com/djphantom",
      spotify: "https://open.spotify.com/artist/djphantom",
      youtube: null,
      tiktok: "https://tiktok.com/@djphantom",
      indieCity: null,
      website: "https://djphantom.io",
    },
  },
  {
    id: "5",
    name: "Ember Waves",
    genre: "Folk",
    followers: 28000,
    monthlyListeners: 180000,
    image: "/folk-singer-songwriter-with-acoustic-guitar-warm-l.jpg",
    popularity: 64,
    location: "Nashville, TN",
    badge: "New",
    bio: "Indie folk singer-songwriter crafting intimate acoustic narratives.",
    socialLinks: {
      instagram: "https://instagram.com/emberwaves",
      spotify: "https://open.spotify.com/artist/emberwaves",
      youtube: "https://youtube.com/@emberwaves",
      tiktok: null,
      indieCity: "https://indiecity.com/emberwaves",
      website: null,
    },
  },
  {
    id: "6",
    name: "Synthesize",
    genre: "Electronic",
    followers: 156000,
    monthlyListeners: 1200000,
    image: "/electronic-music-producer-in-studio-with-synths.jpg",
    popularity: 91,
    location: "London, UK",
    badge: "Trending",
    bio: "Melodic house and techno producer known for euphoric festival anthems.",
    socialLinks: {
      instagram: "https://instagram.com/synthesize",
      spotify: "https://open.spotify.com/artist/synthesize",
      youtube: "https://youtube.com/@synthesize",
      tiktok: "https://tiktok.com/@synthesize",
      indieCity: null,
      website: "https://synthesize.live",
    },
  },
  {
    id: "7",
    name: "The Midnight Quartet",
    genre: "Jazz",
    followers: 34000,
    monthlyListeners: 210000,
    image: "/jazz-quartet-band-performance-elegant-suits.jpg",
    popularity: 68,
    location: "Chicago, IL",
    badge: null,
    bio: "Classic jazz ensemble reviving the golden era of bebop and swing.",
    socialLinks: {
      instagram: "https://instagram.com/midnightquartet",
      spotify: "https://open.spotify.com/artist/midnightquartet",
      youtube: null,
      tiktok: null,
      indieCity: null,
      website: "https://themidnightquartet.com",
    },
  },
  {
    id: "8",
    name: "Neon Pulse",
    genre: "Alternative",
    followers: 67000,
    monthlyListeners: 480000,
    image: "/alternative-synth-rock-band-neon-purple-lighting.jpg",
    popularity: 76,
    location: "Portland, OR",
    badge: "New",
    bio: "Alternative synth-rock band blending 80s nostalgia with modern production.",
    socialLinks: {
      instagram: "https://instagram.com/neonpulse",
      spotify: "https://open.spotify.com/artist/neonpulse",
      youtube: "https://youtube.com/@neonpulse",
      tiktok: "https://tiktok.com/@neonpulse",
      indieCity: "https://indiecity.com/neonpulse",
      website: null,
    },
  },
  {
    id: "9",
    name: "Skyward",
    genre: "Indie Pop",
    followers: 112000,
    monthlyListeners: 890000,
    image: "/indie-pop-duo-colorful-artistic-portrait.jpg",
    popularity: 83,
    location: "Austin, TX",
    badge: "Local to you",
    bio: "Dreamy indie pop duo creating shimmering soundscapes and catchy hooks.",
    socialLinks: {
      instagram: "https://instagram.com/skywardmusic",
      spotify: "https://open.spotify.com/artist/skyward",
      youtube: "https://youtube.com/@skyward",
      tiktok: "https://tiktok.com/@skywardmusic",
      indieCity: "https://indiecity.com/skyward",
      website: "https://skywardmusic.com",
    },
  },
  {
    id: "10",
    name: "Bass Culture",
    genre: "EDM",
    followers: 203000,
    monthlyListeners: 1500000,
    image: "/edm-artist-on-festival-stage-with-lasers-and-crowd.jpg",
    popularity: 94,
    location: "Miami, FL",
    badge: "Trending",
    bio: "High-energy bass music producer dominating festival stages worldwide.",
    socialLinks: {
      instagram: "https://instagram.com/bassculture",
      spotify: "https://open.spotify.com/artist/bassculture",
      youtube: "https://youtube.com/@bassculture",
      tiktok: "https://tiktok.com/@bassculture",
      indieCity: null,
      website: "https://bassculture.com",
    },
  },
]

export const mockPastEvents = [
  {
    id: "past-1",
    name: "Neon Dreams Tour - LA",
    artist: "Luna Eclipse",
    venue: "The Wiltern",
    city: "Los Angeles, CA",
    date: "2024-12-15",
    time: "8:00 PM",
    genre: "Electronic",
    image: "/electronic-concert-neon-lights.jpg",
    hasMoments: true,
  },
  {
    id: "past-2",
    name: "Eclipse Festival Set",
    artist: "Luna Eclipse",
    venue: "EDC Las Vegas",
    city: "Las Vegas, NV",
    date: "2024-10-20",
    time: "11:00 PM",
    genre: "Electronic",
    image: "/festival-stage-night-lasers.jpg",
    hasMoments: true,
  },
  {
    id: "past-3",
    name: "Intimate Acoustic Night",
    artist: "River Stone",
    venue: "Village Vanguard",
    city: "New York, NY",
    date: "2024-11-08",
    time: "9:00 PM",
    genre: "Jazz",
    image: "/jazz-club-intimate-performance.jpg",
    hasMoments: false,
  },
]

export const mockVenueEvents = [
  {
    id: "venue-1",
    name: "Jazz Night",
    artist: "The Blue Note Quartet",
    venue: "The Blue Room",
    city: "Chicago",
    date: "2025-01-05",
    time: "8:00 PM",
    genre: "Jazz",
    image: "/jazz-club-intimate-performance.jpg",
    price: { min: 25, max: 50 },
    attendance: { projected: 120, capacity: 150 },
    demand: 76,
    createdBy: "venue",
    status: "confirmed",
  },
  {
    id: "venue-2",
    name: "Electronic Fest",
    artist: "Various DJs",
    venue: "The Blue Room",
    city: "Chicago",
    date: "2025-01-12",
    time: "10:00 PM",
    genre: "Electronic",
    image: "/electronic-concert-neon-lights.jpg",
    price: { min: 30, max: 75 },
    attendance: { projected: 280, capacity: 300 },
    demand: 89,
    createdBy: "venue",
    status: "confirmed",
  },
  {
    id: "venue-3",
    name: "Luna Eclipse",
    artist: "Luna Eclipse",
    venue: "The Blue Room",
    city: "Chicago",
    date: "2025-01-15",
    time: "9:00 PM",
    genre: "Electronic",
    image: "/female-electronic-music-dj-artist-with-neon-lights.jpg",
    price: { min: 45, max: 120 },
    attendance: { projected: 250, capacity: 300 },
    demand: 92,
    createdBy: "artist",
    status: "confirmed",
  },
  {
    id: "venue-4",
    name: "Indie Showcase",
    artist: "Local Indie Bands",
    venue: "The Blue Room",
    city: "Chicago",
    date: "2025-01-22",
    time: "7:00 PM",
    genre: "Indie",
    image: "/outdoor-music-festival-summer.jpg",
    price: { min: 20, max: 40 },
    attendance: { projected: 180, capacity: 200 },
    demand: 68,
    createdBy: "venue",
    status: "pending",
  },
  {
    id: "venue-5",
    name: "Rock Revival",
    artist: "The Amplifiers",
    venue: "The Blue Room",
    city: "Chicago",
    date: "2025-01-28",
    time: "8:00 PM",
    genre: "Rock",
    image: "/rock-concert-energetic-crowd.jpg",
    price: { min: 35, max: 70 },
    attendance: { projected: 220, capacity: 250 },
    demand: 81,
    createdBy: "artist",
    status: "confirmed",
  },
]

export const mockPromoterEvents = [
  {
    id: "promo-1",
    name: "Summer Music Summit",
    artist: "Various Artists",
    venue: "Central Park",
    city: "New York",
    date: "2025-02-15",
    time: "2:00 PM",
    genre: "Multi-Genre",
    image: "/outdoor-music-festival-summer.jpg",
    price: { min: 85, max: 250 },
    attendance: { projected: 8500, capacity: 10000 },
    demand: 91,
    createdBy: "promoter",
    status: "confirmed",
  },
  {
    id: "promo-2",
    name: "EDM Night Spectacular",
    artist: "DJ Phantom & Friends",
    venue: "Warehouse 9",
    city: "Los Angeles",
    date: "2025-02-20",
    time: "10:00 PM",
    genre: "Electronic",
    image: "/electronic-concert-neon-lights.jpg",
    price: { min: 55, max: 150 },
    attendance: { projected: 3200, capacity: 4000 },
    demand: 88,
    createdBy: "promoter",
    status: "confirmed",
  },
  {
    id: "promo-3",
    name: "Jazz & Wine Evening",
    artist: "The Blue Note Quartet",
    venue: "The Blue Room",
    city: "Chicago",
    date: "2025-02-25",
    time: "7:00 PM",
    genre: "Jazz",
    image: "/jazz-club-intimate-performance.jpg",
    price: { min: 65, max: 120 },
    attendance: { projected: 180, capacity: 200 },
    demand: 95,
    createdBy: "promoter",
    status: "pending",
  },
  {
    id: "promo-4",
    name: "Rock Revolution Tour",
    artist: "The Amplifiers",
    venue: "The Anthem",
    city: "Washington DC",
    date: "2025-03-01",
    time: "8:00 PM",
    genre: "Rock",
    image: "/rock-concert-energetic-crowd.jpg",
    price: { min: 45, max: 95 },
    attendance: { projected: 2800, capacity: 3500 },
    demand: 82,
    createdBy: "artist",
    status: "confirmed",
  },
  {
    id: "promo-5",
    name: "Indie Collective Showcase",
    artist: "Emerging Artists",
    venue: "Brooklyn Steel",
    city: "New York",
    date: "2025-03-08",
    time: "6:00 PM",
    genre: "Indie",
    image: "/outdoor-music-festival-summer.jpg",
    price: { min: 35, max: 75 },
    attendance: { projected: 1200, capacity: 1500 },
    demand: 74,
    createdBy: "promoter",
    status: "draft",
  },
]

export const mockMoments = [
  {
    id: "1",
    eventId: "1",
    userId: "user1",
    userName: "Sarah M.",
    userAvatar: "/young-woman-avatar.png",
    image: "/concert-crowd-neon-lights-phone-photo.jpg",
    caption: "Incredible energy at Luna Eclipse!",
    likes: 234,
    comments: 18,
    timestamp: "2025-01-15T23:45:00Z",
  },
  {
    id: "2",
    eventId: "2",
    userId: "user2",
    userName: "Marcus J.",
    userAvatar: "/young-man-avatar.png",
    image: "/jazz-club-intimate-atmosphere.jpg",
    caption: "River Stone absolutely killed it tonight",
    likes: 89,
    comments: 7,
    timestamp: "2025-01-18T22:30:00Z",
  },
  {
    id: "3",
    eventId: "1",
    userId: "user3",
    userName: "Alex K.",
    userAvatar: "/young-person-avatar.png",
    image: "/neon-concert-stage-view.jpg",
    caption: "Best light show I've ever seen",
    likes: 156,
    comments: 12,
    timestamp: "2025-01-15T23:30:00Z",
  },
  {
    id: "4",
    eventId: "1",
    userId: "user4",
    userName: "Jordan P.",
    userAvatar: "/smiling-person-avatar.png",
    image: "/crowd-dancing-at-electronic-concert.jpg",
    caption: "The bass drop was insane!",
    likes: 312,
    comments: 24,
    timestamp: "2025-01-15T23:50:00Z",
  },
  {
    id: "5",
    eventId: "3",
    userId: "user5",
    userName: "Taylor R.",
    userAvatar: "/casual-person-avatar.jpg",
    image: "/outdoor-festival-sunset-crowd.jpg",
    caption: "Summer Vibes living up to its name",
    likes: 445,
    comments: 31,
    timestamp: "2025-01-22T19:15:00Z",
  },
  {
    id: "jazz-moment-1",
    eventId: "jazz-1",
    userId: "jazz-fan-1",
    userName: "David L.",
    userAvatar: "/jazz-fan-avatar-1.jpg",
    image: "/jazz-quartet-performance-moment.jpg",
    caption: "Joe Lovano's sax solo gave me chills. Pure mastery!",
    likes: 142,
    comments: 15,
    timestamp: "2025-01-24T22:30:00Z",
  },
  {
    id: "jazz-moment-2",
    eventId: "jazz-1",
    userId: "jazz-fan-2",
    userName: "Rachel S.",
    userAvatar: "/jazz-fan-avatar-2.jpg",
    image: "/village-vanguard-intimate-crowd.jpg",
    caption: "The Village Vanguard never disappoints. Intimate and magical.",
    likes: 98,
    comments: 8,
    timestamp: "2025-01-24T23:15:00Z",
  },
  {
    id: "jazz-moment-3",
    eventId: "jazz-2",
    userId: "jazz-fan-3",
    userName: "Michael R.",
    userAvatar: "/jazz-fan-avatar-3.jpg",
    image: "/smalls-jazz-club-performance.jpg",
    caption: "Discovering new voices in jazz. These artists are incredible!",
    likes: 76,
    comments: 11,
    timestamp: "2025-01-25T21:45:00Z",
  },
  {
    id: "jazz-moment-4",
    eventId: "jazz-2",
    userId: "jazz-fan-4",
    userName: "Lisa T.",
    userAvatar: "/jazz-fan-avatar-4.jpg",
    image: "/jazz-bassist-closeup.jpg",
    caption: "The bass player's technique is phenomenal 🎵",
    likes: 103,
    comments: 9,
    timestamp: "2025-01-25T22:30:00Z",
  },
  {
    id: "jazz-moment-5",
    eventId: "jazz-3",
    userId: "jazz-fan-5",
    userName: "James W.",
    userAvatar: "/jazz-fan-avatar-5.jpg",
    image: "/blue-note-stage-lighting.jpg",
    caption: "Modern jazz at its finest. Blue Note is iconic for a reason.",
    likes: 187,
    comments: 19,
    timestamp: "2025-01-26T22:00:00Z",
  },
  {
    id: "jazz-moment-6",
    eventId: "jazz-3",
    userId: "jazz-fan-6",
    userName: "Sophia M.",
    userAvatar: "/jazz-fan-avatar-6.jpg",
    image: "/jazz-piano-hands-closeup.jpg",
    caption: "The pianist's improvisation was transcendent. What a night!",
    likes: 134,
    comments: 14,
    timestamp: "2025-01-26T23:20:00Z",
  },
  // Demo conviction event moments
  {
    id: "demo-moment-1",
    eventId: "neon-dreams-demo",
    userId: "fan1",
    userName: "Emma Wilson",
    userAvatar: "/woman-avatar-profile.jpg",
    image: "/electronic-concert-neon-lights.jpg",
    caption: "Neon Dreams lighting was absolutely unreal tonight!",
    likes: 189,
    comments: 16,
    timestamp: "2026-02-25T22:30:00Z",
  },
  {
    id: "demo-moment-2",
    eventId: "neon-dreams-demo",
    userId: "fan2",
    userName: "Chris Davis",
    userAvatar: "/man-avatar-casual.jpg",
    image: "/neon-concert-stage-view.jpg",
    caption: "Stage view from the front row. Mind blown.",
    likes: 245,
    comments: 22,
    timestamp: "2026-02-25T23:00:00Z",
  },
  {
    id: "demo-moment-3",
    eventId: "neon-dreams-demo",
    userId: "user3",
    userName: "Alex K.",
    userAvatar: "/young-person-avatar.png",
    image: "/crowd-dancing-at-electronic-concert.jpg",
    caption: "The crowd was on another level tonight",
    likes: 167,
    comments: 12,
    timestamp: "2026-02-25T23:15:00Z",
  },
  {
    id: "demo-moment-4",
    eventId: "acoustic-sessions-demo",
    userId: "jazz-fan-1",
    userName: "David L.",
    userAvatar: "/jazz-fan-avatar-1.jpg",
    image: "/acoustic-folk-performance-intimate-venue.jpg",
    caption: "Willow & The Waves absolutely captivated the room",
    likes: 112,
    comments: 9,
    timestamp: "2026-02-25T22:00:00Z",
  },
  {
    id: "demo-moment-5",
    eventId: "acoustic-sessions-demo",
    userId: "jazz-fan-2",
    userName: "Rachel S.",
    userAvatar: "/jazz-fan-avatar-2.jpg",
    image: "/jazz-club-intimate-performance.jpg",
    caption: "Harmony Hall is the perfect venue for this kind of show",
    likes: 87,
    comments: 7,
    timestamp: "2026-02-25T22:30:00Z",
  },
  {
    id: "demo-moment-6",
    eventId: "lunar-bloom-demo",
    userId: "fan2",
    userName: "Chris Davis",
    userAvatar: "/man-avatar-casual.jpg",
    image: "/neon-club-electronic-music-night.jpg",
    caption: "Warehouse 9 transformed into another dimension",
    likes: 203,
    comments: 18,
    timestamp: "2026-02-27T23:00:00Z",
  },
  {
    id: "demo-moment-7",
    eventId: "lunar-bloom-demo",
    userId: "jazz-fan-12",
    userName: "Maya S.",
    userAvatar: "/jazz-fan-avatar-12.jpg",
    image: "/electronic-music-concert-stage-lights.jpg",
    caption: "Lunar Bloom's set was absolutely hypnotic",
    likes: 178,
    comments: 14,
    timestamp: "2026-02-27T23:30:00Z",
  },
  {
    id: "demo-moment-8",
    eventId: "static-youth-demo",
    userId: "fan3",
    userName: "Jamie Lee",
    userAvatar: "/person-smiling-avatar.jpg",
    image: "/indie-rock-showcase-small-venue.jpg",
    caption: "Static Youth brought the energy at The Lot Radio!",
    likes: 64,
    comments: 5,
    timestamp: "2026-02-26T20:30:00Z",
  },
  {
    id: "demo-moment-9",
    eventId: "summer-vibes-demo",
    userId: "fan1",
    userName: "Emma Wilson",
    userAvatar: "/woman-avatar-profile.jpg",
    image: "/outdoor-festival-sunset-crowd.jpg",
    caption: "Summer Vibes Festival sunset was magical",
    likes: 356,
    comments: 28,
    timestamp: "2026-06-14T19:00:00Z",
  },
  {
    id: "demo-moment-10",
    eventId: "summer-vibes-demo",
    userId: "jazz-fan-5",
    userName: "James W.",
    userAvatar: "/jazz-fan-avatar-5.jpg",
    image: "/outdoor-music-festival-summer.jpg",
    caption: "Perfect weather, perfect vibes, perfect lineup",
    likes: 412,
    comments: 31,
    timestamp: "2026-06-14T20:00:00Z",
  },
  {
    id: "demo-moment-11",
    eventId: "summer-vibes-demo",
    userId: "user3",
    userName: "Alex K.",
    userAvatar: "/young-person-avatar.png",
    image: "/summer-music-festival-outdoor-stage-sunset-crowd.jpg",
    caption: "Prospect Park Bandshell never looked better",
    likes: 289,
    comments: 19,
    timestamp: "2026-06-14T21:00:00Z",
  },
  {
    id: "demo-moment-12",
    eventId: "velvet-echo-demo",
    userId: "jazz-fan-6",
    userName: "Sophia M.",
    userAvatar: "/jazz-fan-avatar-6.jpg",
    image: "/concert-poster-artwork-neon.jpg",
    caption: "Velvet Echo's synth-pop magic at Le Poisson Rouge",
    likes: 98,
    comments: 8,
    timestamp: "2026-03-07T22:30:00Z",
  },
  {
    id: "demo-moment-13",
    eventId: "velvet-echo-demo",
    userId: "jazz-fan-9",
    userName: "Carlos M.",
    userAvatar: "/jazz-fan-avatar-9.jpg",
    image: "/concert-poster-art-vaporwave.jpg",
    caption: "The visual art paired with the music was incredible",
    likes: 76,
    comments: 6,
    timestamp: "2026-03-07T23:00:00Z",
  },
]

export const mockEventAttendees = [
  {
    eventId: "1",
    attendees: [
      { id: "fan1", name: "Emma Wilson", avatar: "/woman-avatar-profile.jpg", isFriend: true },
      { id: "fan2", name: "Chris Davis", avatar: "/man-avatar-casual.jpg", isFriend: true },
      { id: "fan3", name: "Jamie Lee", avatar: "/person-smiling-avatar.jpg", isFriend: false },
      { id: "user1", name: "Sarah M.", avatar: "/young-woman-avatar.png", isFriend: false },
      { id: "user3", name: "Alex K.", avatar: "/young-person-avatar.png", isFriend: false },
      { id: "user4", name: "Jordan P.", avatar: "/smiling-person-avatar.png", isFriend: false },
    ],
  },
  {
    eventId: "2",
    attendees: [
      { id: "fan4", name: "Morgan Chen", avatar: "/asian-person-avatar.jpg", isFriend: false },
      { id: "user2", name: "Marcus J.", avatar: "/young-man-avatar.png", isFriend: false },
    ],
  },
  {
    eventId: "3",
    attendees: [
      { id: "fan1", name: "Emma Wilson", avatar: "/woman-avatar-profile.jpg", isFriend: true },
      { id: "fan6", name: "Sam Rivera", avatar: "/creative-person-avatar.jpg", isFriend: false },
      { id: "user5", name: "Taylor R.", avatar: "/casual-person-avatar.jpg", isFriend: false },
    ],
  },
  {
    eventId: "jazz-1",
    attendees: [
      { id: "jazz-fan-1", name: "David L.", avatar: "/jazz-fan-avatar-1.jpg", isFriend: true },
      { id: "jazz-fan-2", name: "Rachel S.", avatar: "/jazz-fan-avatar-2.jpg", isFriend: true },
      { id: "jazz-fan-7", name: "Thomas K.", avatar: "/jazz-fan-avatar-7.jpg", isFriend: false },
      { id: "jazz-fan-8", name: "Nina P.", avatar: "/jazz-fan-avatar-8.jpg", isFriend: false },
      { id: "jazz-fan-9", name: "Carlos M.", avatar: "/jazz-fan-avatar-9.jpg", isFriend: false },
      { id: "jazz-fan-10", name: "Elena R.", avatar: "/jazz-fan-avatar-10.jpg", isFriend: true },
    ],
  },
  {
    eventId: "jazz-2",
    attendees: [
      { id: "jazz-fan-3", name: "Michael R.", avatar: "/jazz-fan-avatar-3.jpg", isFriend: true },
      { id: "jazz-fan-4", name: "Lisa T.", avatar: "/jazz-fan-avatar-4.jpg", isFriend: false },
      { id: "jazz-fan-11", name: "Kevin H.", avatar: "/jazz-fan-avatar-11.jpg", isFriend: false },
      { id: "jazz-fan-12", name: "Maya S.", avatar: "/jazz-fan-avatar-12.jpg", isFriend: true },
      { id: "jazz-fan-13", name: "Andre B.", avatar: "/jazz-fan-avatar-13.jpg", isFriend: false },
    ],
  },
  {
    eventId: "jazz-3",
    attendees: [
      { id: "jazz-fan-5", name: "James W.", avatar: "/jazz-fan-avatar-5.jpg", isFriend: true },
      { id: "jazz-fan-6", name: "Sophia M.", avatar: "/jazz-fan-avatar-6.jpg", isFriend: true },
      { id: "jazz-fan-14", name: "Ryan C.", avatar: "/jazz-fan-avatar-14.jpg", isFriend: false },
      { id: "jazz-fan-15", name: "Olivia D.", avatar: "/jazz-fan-avatar-15.jpg", isFriend: false },
      { id: "jazz-fan-16", name: "Marcus T.", avatar: "/jazz-fan-avatar-16.jpg", isFriend: true },
      { id: "jazz-fan-17", name: "Isabella F.", avatar: "/jazz-fan-avatar-17.jpg", isFriend: false },
    ],
  },
  // Demo conviction events
  {
    eventId: "neon-dreams-demo",
    attendees: [
      { id: "fan1", name: "Emma Wilson", avatar: "/woman-avatar-profile.jpg", isFriend: true },
      { id: "fan2", name: "Chris Davis", avatar: "/man-avatar-casual.jpg", isFriend: true },
      { id: "fan3", name: "Jamie Lee", avatar: "/person-smiling-avatar.jpg", isFriend: false },
      { id: "user1", name: "Sarah M.", avatar: "/young-woman-avatar.png", isFriend: false },
      { id: "user3", name: "Alex K.", avatar: "/young-person-avatar.png", isFriend: false },
    ],
  },
  {
    eventId: "acoustic-sessions-demo",
    attendees: [
      { id: "jazz-fan-1", name: "David L.", avatar: "/jazz-fan-avatar-1.jpg", isFriend: true },
      { id: "jazz-fan-2", name: "Rachel S.", avatar: "/jazz-fan-avatar-2.jpg", isFriend: false },
      { id: "fan1", name: "Emma Wilson", avatar: "/woman-avatar-profile.jpg", isFriend: true },
      { id: "jazz-fan-10", name: "Elena R.", avatar: "/jazz-fan-avatar-10.jpg", isFriend: false },
    ],
  },
  {
    eventId: "lunar-bloom-demo",
    attendees: [
      { id: "user4", name: "Jordan P.", avatar: "/smiling-person-avatar.png", isFriend: false },
      { id: "fan2", name: "Chris Davis", avatar: "/man-avatar-casual.jpg", isFriend: true },
      { id: "jazz-fan-7", name: "Thomas K.", avatar: "/jazz-fan-avatar-7.jpg", isFriend: false },
      { id: "jazz-fan-11", name: "Kevin H.", avatar: "/jazz-fan-avatar-11.jpg", isFriend: false },
      { id: "jazz-fan-12", name: "Maya S.", avatar: "/jazz-fan-avatar-12.jpg", isFriend: true },
      { id: "user1", name: "Sarah M.", avatar: "/young-woman-avatar.png", isFriend: false },
    ],
  },
  {
    eventId: "static-youth-demo",
    attendees: [
      { id: "jazz-fan-3", name: "Michael R.", avatar: "/jazz-fan-avatar-3.jpg", isFriend: false },
      { id: "jazz-fan-4", name: "Lisa T.", avatar: "/jazz-fan-avatar-4.jpg", isFriend: false },
      { id: "fan3", name: "Jamie Lee", avatar: "/person-smiling-avatar.jpg", isFriend: true },
    ],
  },
  {
    eventId: "summer-vibes-demo",
    attendees: [
      { id: "fan1", name: "Emma Wilson", avatar: "/woman-avatar-profile.jpg", isFriend: true },
      { id: "fan2", name: "Chris Davis", avatar: "/man-avatar-casual.jpg", isFriend: true },
      { id: "user1", name: "Sarah M.", avatar: "/young-woman-avatar.png", isFriend: false },
      { id: "user3", name: "Alex K.", avatar: "/young-person-avatar.png", isFriend: false },
      { id: "jazz-fan-5", name: "James W.", avatar: "/jazz-fan-avatar-5.jpg", isFriend: true },
      { id: "jazz-fan-8", name: "Nina P.", avatar: "/jazz-fan-avatar-8.jpg", isFriend: false },
      { id: "jazz-fan-13", name: "Andre B.", avatar: "/jazz-fan-avatar-13.jpg", isFriend: false },
    ],
  },
  {
    eventId: "velvet-echo-demo",
    attendees: [
      { id: "jazz-fan-6", name: "Sophia M.", avatar: "/jazz-fan-avatar-6.jpg", isFriend: true },
      { id: "jazz-fan-9", name: "Carlos M.", avatar: "/jazz-fan-avatar-9.jpg", isFriend: false },
      { id: "fan3", name: "Jamie Lee", avatar: "/person-smiling-avatar.jpg", isFriend: false },
      { id: "jazz-fan-15", name: "Olivia D.", avatar: "/jazz-fan-avatar-15.jpg", isFriend: false },
    ],
  },
]

export const mockUserMoments = [
  {
    id: "um1",
    eventId: "1",
    image: "/concert-crowd-neon-lights-phone-photo.jpg",
    caption: "Amazing night!",
    likes: 45,
  },
  {
    id: "um2",
    eventId: "3",
    image: "/outdoor-festival-sunset-crowd.jpg",
    caption: "Festival vibes",
    likes: 78,
  },
]

export const mockToolCalls = [
  {
    tool: "mcp.events_supabase",
    status: "completed",
    duration: "124ms",
    result: "Retrieved 847 events within 50mi radius",
  },
  {
    tool: "mcp.artist_popularity",
    status: "completed",
    duration: "89ms",
    result: "Calculated popularity scores for 23 artists",
  },
  {
    tool: "mcp.market_demand",
    status: "completed",
    duration: "156ms",
    result: "Demand index: 87/100 for Electronic genre",
  },
  {
    tool: "mcp.local_competition",
    status: "completed",
    duration: "201ms",
    result: "3 competing events on same date",
  },
]

export const mockGroupBuys = [
  {
    id: "gb1",
    eventId: "1",
    eventName: "Neon Dreams Tour",
    eventImage: "/electronic-concert-neon-lights.jpg",
    eventDate: "2025-01-15",
    eventVenue: "The Anthem",
    ticketTier: "Premium",
    originalPrice: 85,
    groupPrice: 65,
    minSize: 4,
    maxSize: 8,
    currentSize: 3,
    creatorId: "fan1",
    creatorName: "Emma Wilson",
    status: "active",
    expiresAt: "2025-01-14T20:00:00Z",
    joinCode: "NEON2025",
    members: [
      { id: "fan1", name: "Emma Wilson", avatar: "/woman-avatar-profile.jpg", isCreator: true },
      { id: "fan2", name: "Chris Davis", avatar: "/man-avatar-casual.jpg", isCreator: false },
      { id: "fan3", name: "Jamie Lee", avatar: "/person-smiling-avatar.jpg", isCreator: false },
    ],
  },
  {
    id: "gb2",
    eventId: "3",
    eventName: "Summer Vibes Festival",
    eventImage: "/outdoor-music-festival-summer.jpg",
    eventDate: "2025-01-22",
    eventVenue: "Pier 17",
    ticketTier: "General Admission",
    originalPrice: 75,
    groupPrice: 55,
    minSize: 5,
    maxSize: 10,
    currentSize: 5,
    creatorId: "fan6",
    creatorName: "Sam Rivera",
    status: "complete",
    expiresAt: "2025-01-21T16:00:00Z",
    joinCode: "VIBES2025",
    members: [
      { id: "fan6", name: "Sam Rivera", avatar: "/creative-person-avatar.jpg", isCreator: true },
      { id: "fan1", name: "Emma Wilson", avatar: "/woman-avatar-profile.jpg", isCreator: false },
      { id: "fan4", name: "Morgan Chen", avatar: "/asian-person-avatar.jpg", isCreator: false },
      { id: "fan5", name: "Riley Thompson", avatar: "/young-professional-avatar.jpg", isCreator: false },
      { id: "user1", name: "Sarah M.", avatar: "/young-woman-avatar.png", isCreator: false },
    ],
  },
]

export const mockGroupBuyChat = [
  {
    id: "gbc1",
    groupBuyId: "gb1",
    userId: "fan1",
    userName: "Emma Wilson",
    userAvatar: "/woman-avatar-profile.jpg",
    text: "Hey everyone! Let's get this group filled up!",
    timestamp: "2025-01-12T14:30:00Z",
  },
  {
    id: "gbc2",
    groupBuyId: "gb1",
    userId: "fan2",
    userName: "Chris Davis",
    userAvatar: "/man-avatar-casual.jpg",
    text: "I'm in! Luna Eclipse is gonna be amazing",
    timestamp: "2025-01-12T14:35:00Z",
  },
  {
    id: "gbc3",
    groupBuyId: "gb1",
    userId: "fan3",
    userName: "Jamie Lee",
    userAvatar: "/person-smiling-avatar.jpg",
    text: "Just joined! One more person and we hit the minimum",
    timestamp: "2025-01-12T15:00:00Z",
  },
  {
    id: "gbc4",
    groupBuyId: "gb1",
    userId: "fan1",
    userName: "Emma Wilson",
    userAvatar: "/woman-avatar-profile.jpg",
    text: "Share the link with your friends! Code is NEON2025",
    timestamp: "2025-01-12T15:05:00Z",
  },
]

export const mockEventChat = [
  {
    id: "ec1",
    eventId: "1",
    userId: "fan1",
    userName: "Emma Wilson",
    userAvatar: "/woman-avatar-profile.jpg",
    text: "Who else is going to this?! So excited!",
    timestamp: "2025-01-10T10:00:00Z",
  },
  {
    id: "ec2",
    eventId: "1",
    userId: "fan2",
    userName: "Chris Davis",
    userAvatar: "/man-avatar-casual.jpg",
    text: "I'll be there! Premium section",
    timestamp: "2025-01-10T10:15:00Z",
  },
  {
    id: "ec3",
    eventId: "1",
    userId: "artist1",
    userName: "Luna Eclipse",
    userAvatar: "/female-electronic-music-dj-artist-with-neon-lights.jpg",
    text: "Can't wait to see you all! I've got some surprises planned for this show 🎵",
    timestamp: "2025-01-11T18:00:00Z",
    isArtist: true,
  },
  {
    id: "ec4",
    eventId: "1",
    userId: "venue1",
    userName: "The Anthem",
    userAvatar: "/music-venue-logo.png",
    text: "Doors open at 7PM. VIP entrance on the left side of the building.",
    timestamp: "2025-01-12T12:00:00Z",
    isVenue: true,
  },
  {
    id: "ec5",
    eventId: "1",
    userId: "fan3",
    userName: "Jamie Lee",
    userAvatar: "/person-smiling-avatar.jpg",
    text: "Anyone want to meet up before the show?",
    timestamp: "2025-01-13T09:30:00Z",
  },
  // Demo conviction event chats
  {
    id: "ec-nd-1",
    eventId: "neon-dreams-demo",
    userId: "fan1",
    userName: "Emma Wilson",
    userAvatar: "/woman-avatar-profile.jpg",
    text: "Just secured my tickets! Who else is going tonight?",
    timestamp: "2026-02-24T14:00:00Z",
  },
  {
    id: "ec-nd-2",
    eventId: "neon-dreams-demo",
    userId: "fan2",
    userName: "Chris Davis",
    userAvatar: "/man-avatar-casual.jpg",
    text: "I'll be there! Heard the visuals are going to be insane",
    timestamp: "2026-02-24T14:15:00Z",
  },
  {
    id: "ec-nd-3",
    eventId: "neon-dreams-demo",
    userId: "user3",
    userName: "Alex K.",
    userAvatar: "/young-person-avatar.png",
    text: "The Atlas Room is such a great venue for electronic shows. See you all there!",
    timestamp: "2026-02-24T16:00:00Z",
  },
  {
    id: "ec-nd-4",
    eventId: "neon-dreams-demo",
    userId: "fan3",
    userName: "Jamie Lee",
    userAvatar: "/person-smiling-avatar.jpg",
    text: "Anyone know what time the opening act starts?",
    timestamp: "2026-02-25T10:00:00Z",
  },
  {
    id: "ec-as-1",
    eventId: "acoustic-sessions-demo",
    userId: "jazz-fan-1",
    userName: "David L.",
    userAvatar: "/jazz-fan-avatar-1.jpg",
    text: "Willow & The Waves live is a must-see. Their harmonies are incredible.",
    timestamp: "2026-02-24T12:00:00Z",
  },
  {
    id: "ec-as-2",
    eventId: "acoustic-sessions-demo",
    userId: "fan1",
    userName: "Emma Wilson",
    userAvatar: "/woman-avatar-profile.jpg",
    text: "Harmony Hall has the best acoustics for this kind of show!",
    timestamp: "2026-02-24T13:30:00Z",
  },
  {
    id: "ec-as-3",
    eventId: "acoustic-sessions-demo",
    userId: "jazz-fan-2",
    userName: "Rachel S.",
    userAvatar: "/jazz-fan-avatar-2.jpg",
    text: "Getting there early for a good seat. Doors at 9 right?",
    timestamp: "2026-02-25T08:00:00Z",
  },
  {
    id: "ec-lb-1",
    eventId: "lunar-bloom-demo",
    userId: "fan2",
    userName: "Chris Davis",
    userAvatar: "/man-avatar-casual.jpg",
    text: "Warehouse 9 late night electronic? Count me in.",
    timestamp: "2026-02-26T18:00:00Z",
  },
  {
    id: "ec-lb-2",
    eventId: "lunar-bloom-demo",
    userId: "jazz-fan-12",
    userName: "Maya S.",
    userAvatar: "/jazz-fan-avatar-12.jpg",
    text: "Lunar Bloom's last set was mind-blowing. This one will be even better.",
    timestamp: "2026-02-26T19:00:00Z",
  },
  {
    id: "ec-lb-3",
    eventId: "lunar-bloom-demo",
    userId: "jazz-fan-7",
    userName: "Thomas K.",
    userAvatar: "/jazz-fan-avatar-7.jpg",
    text: "Anyone want to split a ride there?",
    timestamp: "2026-02-27T15:00:00Z",
  },
  {
    id: "ec-sy-1",
    eventId: "static-youth-demo",
    userId: "fan3",
    userName: "Jamie Lee",
    userAvatar: "/person-smiling-avatar.jpg",
    text: "The Lot Radio is such a gem. Perfect for indie shows.",
    timestamp: "2026-02-25T12:00:00Z",
  },
  {
    id: "ec-sy-2",
    eventId: "static-youth-demo",
    userId: "jazz-fan-3",
    userName: "Michael R.",
    userAvatar: "/jazz-fan-avatar-3.jpg",
    text: "Just discovered Static Youth. Their EP is fire!",
    timestamp: "2026-02-25T14:00:00Z",
  },
  {
    id: "ec-sv-1",
    eventId: "summer-vibes-demo",
    userId: "fan1",
    userName: "Emma Wilson",
    userAvatar: "/woman-avatar-profile.jpg",
    text: "Prospect Park in the summer is literally perfect for a festival!",
    timestamp: "2026-06-10T10:00:00Z",
  },
  {
    id: "ec-sv-2",
    eventId: "summer-vibes-demo",
    userId: "jazz-fan-5",
    userName: "James W.",
    userAvatar: "/jazz-fan-avatar-5.jpg",
    text: "The lineup is stacked. Can't wait for this one.",
    timestamp: "2026-06-10T12:00:00Z",
  },
  {
    id: "ec-sv-3",
    eventId: "summer-vibes-demo",
    userId: "fan2",
    userName: "Chris Davis",
    userAvatar: "/man-avatar-casual.jpg",
    text: "Bringing sunscreen and good vibes! Who's joining our crew?",
    timestamp: "2026-06-12T09:00:00Z",
  },
  {
    id: "ec-sv-4",
    eventId: "summer-vibes-demo",
    userId: "user3",
    userName: "Alex K.",
    userAvatar: "/young-person-avatar.png",
    text: "Set up a group buy if anyone wants to save on tickets!",
    timestamp: "2026-06-12T11:00:00Z",
  },
  {
    id: "ec-ve-1",
    eventId: "velvet-echo-demo",
    userId: "jazz-fan-6",
    userName: "Sophia M.",
    userAvatar: "/jazz-fan-avatar-6.jpg",
    text: "Velvet Echo at Le Poisson Rouge is going to be dreamy",
    timestamp: "2026-03-05T16:00:00Z",
  },
  {
    id: "ec-ve-2",
    eventId: "velvet-echo-demo",
    userId: "jazz-fan-9",
    userName: "Carlos M.",
    userAvatar: "/jazz-fan-avatar-9.jpg",
    text: "Love their synth-pop sound. This venue is a perfect match.",
    timestamp: "2026-03-06T10:00:00Z",
  },
  {
    id: "ec-ve-3",
    eventId: "velvet-echo-demo",
    userId: "fan3",
    userName: "Jamie Lee",
    userAvatar: "/person-smiling-avatar.jpg",
    text: "Third time seeing them live. They keep getting better!",
    timestamp: "2026-03-06T14:00:00Z",
  },
]

export const mockFans = [
  {
    id: "fan-1",
    name: "Sarah Chen",
    username: "@sarahchen",
    avatar: "/fan-avatars/sarah-chen.jpg",
    image: "/fan-avatars/sarah-chen.jpg",
    mutualFriends: 12,
    isFriend: true,
    isFollower: true,
    isFollowing: true,
    eventsAttended: 24,
    favoriteGenres: ["Jazz", "Soul"],
    bio: "Live music enthusiast, jazz lover",
  },
  {
    id: "fan-2",
    name: "Marcus Johnson",
    username: "@marcusj",
    avatar: "/fan-avatars/marcus-johnson.jpg",
    image: "/fan-avatars/marcus-johnson.jpg",
    mutualFriends: 8,
    isFriend: true,
    isFollower: true,
    isFollowing: true,
    eventsAttended: 31,
    favoriteGenres: ["Jazz", "Blues"],
    bio: "Jazz collector, Blue Note regular",
  },
  {
    id: "fan-3",
    name: "Emily Rodriguez",
    username: "@emilyrod",
    avatar: "/fan-avatars/emily-rodriguez.jpg",
    image: "/fan-avatars/emily-rodriguez.jpg",
    mutualFriends: 15,
    isFriend: true,
    isFollower: true,
    isFollowing: true,
    eventsAttended: 18,
    favoriteGenres: ["Electronic", "Indie"],
    bio: "Concert photographer",
  },
  {
    id: "fan-4",
    name: "Alex Kim",
    username: "@alexkim",
    avatar: "/fan-avatars/alex-kim.jpg",
    image: "/fan-avatars/alex-kim.jpg",
    mutualFriends: 5,
    isFriend: false,
    isFollower: true,
    isFollowing: false,
    eventsAttended: 42,
    favoriteGenres: ["Rock", "Alternative"],
    bio: "Music festival fanatic",
  },
  {
    id: "fan-5",
    name: "Jordan Taylor",
    username: "@jordantaylor",
    avatar: "/fan-avatars/jordan-taylor.jpg",
    image: "/fan-avatars/jordan-taylor.jpg",
    mutualFriends: 3,
    isFriend: false,
    isFollower: false,
    isFollowing: true,
    eventsAttended: 19,
    favoriteGenres: ["Hip Hop", "R&B"],
    bio: "Vinyl collector",
  },
  {
    id: "fan-6",
    name: "Priya Patel",
    username: "@priyapatel",
    avatar: "/fan-avatars/priya-patel.jpg",
    image: "/fan-avatars/priya-patel.jpg",
    mutualFriends: 0,
    isFriend: false,
    isFollower: false,
    isFollowing: false,
    eventsAttended: 7,
    favoriteGenres: ["Classical", "Jazz"],
    bio: "New to the scene",
  },
]

export const mockFriendRequests = [
  {
    id: "req-1",
    user: {
      id: "fan-7",
      name: "Chris Martinez",
      username: "@chrism",
      image: "/jazz-fan-avatar-7.jpg",
      mutualFriends: 4,
    },
    timestamp: "2 hours ago",
  },
  {
    id: "req-2",
    user: {
      id: "fan-8",
      name: "Sam Wilson",
      username: "@samw",
      image: "/jazz-fan-avatar-8.jpg",
      mutualFriends: 2,
    },
    timestamp: "1 day ago",
  },
]

export const mockFriendChats = [
  {
    friendId: "fan-1",
    messages: [
      {
        id: "msg-1",
        sender: "fan-1",
        text: "Are you going to the Joe Lovano show this weekend?",
        timestamp: "10:30 AM",
      },
      {
        id: "msg-2",
        sender: "me",
        text: "Yes! I got tickets for Saturday. You?",
        timestamp: "10:32 AM",
      },
      {
        id: "msg-3",
        sender: "fan-1",
        text: "Same here! Want to grab dinner before?",
        timestamp: "10:35 AM",
      },
    ],
  },
  {
    friendId: "fan-2",
    messages: [
      {
        id: "msg-4",
        sender: "fan-2",
        text: "Check out this new jazz album I found",
        timestamp: "Yesterday",
      },
    ],
  },
]

export const mockFestivalEvents = []

export const mockSearchHistory = [
  {
    id: "search-1",
    query: "Jazz in New York this weekend",
    summary:
      "Found 4 highly recommended jazz events featuring established and rising artists at iconic venues like Village Vanguard and Blue Note.",
    timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    results: 4,
    saved: true,
    eventIds: ["jazz-1", "jazz-2", "jazz-3"], // Show the 3 jazz events
  },
  {
    id: "search-2",
    query: "Electronic music festivals near me in summer",
    summary:
      "Discovered 12 electronic music events including major festivals and club nights with artists like Luna Eclipse and DJ Phantom.",
    timestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    results: 12,
    saved: false,
    eventIds: ["1", "4", "3"], // Show Neon Dreams Tour (Electronic), Underground Beats (Techno), Summer Vibes Festival
  },
  {
    id: "search-3",
    query: "Indie bands with fair ticketing",
    summary:
      "Located 8 indie concerts with Fair Access protection, ensuring tickets reach real fans instead of scalpers.",
    timestamp: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    results: 8,
    saved: true,
    eventIds: ["3", "2", "1"], // Show Summer Vibes Festival (Indie Pop), Acoustic Sessions, Neon Dreams Tour
  },
]

export const mockContracts = [
  {
    id: "SC-001",
    eventTitle: "Neon Dreams Tour",
    eventDate: "2025-01-15",
    status: "active",
    stakeholders: [
      { role: "Artist", name: "Luna Eclipse", percentage: 60, wallet: "0x1a2b...3c4d" },
      { role: "Venue", name: "The Anthem", percentage: 25, wallet: "0x5e6f...7g8h" },
      { role: "Promoter", name: "Live Nation", percentage: 15, wallet: "0x9i0j...1k2l" },
    ],
    settlementMethod: "USDC (Polygon)",
  },
  {
    id: "SC-002",
    eventTitle: "Acoustic Sessions",
    eventDate: "2025-01-18",
    status: "active",
    stakeholders: [
      { role: "Artist", name: "River Stone", percentage: 70, wallet: "0x3m4n...5o6p" },
      { role: "Venue", name: "Blue Note", percentage: 30, wallet: "0x7q8r...9s0t" },
    ],
    settlementMethod: "ETH (Mainnet)",
  },
  {
    id: "SC-003",
    eventTitle: "Summer Vibes Festival",
    eventDate: "2025-01-22",
    status: "pending",
    stakeholders: [
      { role: "Promoter", name: "Festival Group", percentage: 40, wallet: "0x1u2v...3w4x" },
      { role: "Venue", name: "Pier 17", percentage: 35, wallet: "0x5y6z...7a8b" },
      { role: "Artists", name: "Multiple Artists", percentage: 25, wallet: "0x9c0d...1e2f" },
    ],
    settlementMethod: "USDC (Polygon)",
  },
  {
    id: "SC-004",
    eventTitle: "Joe Lovano Quartet",
    eventDate: "2025-01-31",
    status: "active",
    stakeholders: [
      { role: "Artist", name: "Joe Lovano Quartet", percentage: 65, wallet: "0x3g4h...5i6j" },
      { role: "Venue", name: "Village Vanguard", percentage: 35, wallet: "0x7k8l...9m0n" },
    ],
    settlementMethod: "USDC (Polygon)",
  },
  {
    id: "SC-005",
    eventTitle: "Underground Beats",
    eventDate: "2025-01-25",
    status: "draft",
    stakeholders: [
      { role: "Artist", name: "DJ Phantom", percentage: 55, wallet: "0x1o2p...3q4r" },
      { role: "Venue", name: "Warehouse 9", percentage: 30, wallet: "0x5s6t...7u8v" },
      { role: "Promoter", name: "Underground Collective", percentage: 15, wallet: "0x9w0x...1y2z" },
    ],
    settlementMethod: "ETH (Mainnet)",
  },
]

export const mockMomentComments = [
  {
    id: "comment-1",
    momentId: "1",
    userId: "fan1",
    userName: "Emma Wilson",
    userAvatar: "/woman-avatar-profile.jpg",
    text: "This was the best concert of my life! The energy was unreal 🔥",
    timestamp: "2025-01-16T00:15:00Z",
    isArtist: false,
    isVenue: false,
  },
  {
    id: "comment-2",
    momentId: "1",
    userId: "artist1",
    userName: "Luna Eclipse",
    userAvatar: "/female-electronic-music-dj-artist-with-neon-lights.jpg",
    text: "Thank you all for an incredible night! You were amazing 💜",
    timestamp: "2025-01-16T10:30:00Z",
    isArtist: true,
    isVenue: false,
  },
  {
    id: "comment-3",
    momentId: "2",
    userId: "fan2",
    userName: "Chris Davis",
    userAvatar: "/man-avatar-casual.jpg",
    text: "River Stone's improv was phenomenal. True jazz mastery.",
    timestamp: "2025-01-19T00:45:00Z",
    isArtist: false,
    isVenue: false,
  },
  {
    id: "comment-4",
    momentId: "3",
    userId: "venue1",
    userName: "The Anthem",
    userAvatar: "/music-venue-logo.png",
    text: "Thanks for sharing! Hope to see you at our next show 🎵",
    timestamp: "2025-01-16T08:00:00Z",
    isArtist: false,
    isVenue: true,
  },
  {
    id: "comment-5",
    momentId: "4",
    userId: "fan3",
    userName: "Jamie Lee",
    userAvatar: "/person-smiling-avatar.jpg",
    text: "That bass drop shook my entire soul! Epic night",
    timestamp: "2025-01-16T01:20:00Z",
    isArtist: false,
    isVenue: false,
  },
  {
    id: "comment-6",
    momentId: "jazz-moment-1",
    userId: "jazz-fan-2",
    userName: "Rachel S.",
    userAvatar: "/jazz-fan-avatar-2.jpg",
    text: "I got goosebumps during that solo. Absolutely incredible!",
    timestamp: "2025-01-25T00:00:00Z",
    isArtist: false,
    isVenue: false,
  },
  {
    id: "comment-7",
    momentId: "jazz-moment-3",
    userId: "jazz-fan-5",
    userName: "James W.",
    userAvatar: "/jazz-fan-avatar-5.jpg",
    text: "Rising Voices is the future of jazz. So much talent on one stage!",
    timestamp: "2025-01-26T00:30:00Z",
    isArtist: false,
    isVenue: false,
  },
]

export const mockFriendActivity = [
  {
    id: "fan1",
    eventId: "1",
    userName: "Emma Wilson",
    userAvatar: "/woman-avatar-profile.jpg",
    action: "posted a moment",
    timestamp: "2025-01-15T23:45:00Z",
  },
  {
    id: "fan2",
    eventId: "1",
    userName: "Chris Davis",
    userAvatar: "/man-avatar-casual.jpg",
    action: "liked this event",
    timestamp: "2025-01-15T20:30:00Z",
  },
  {
    id: "fan3",
    eventId: "2",
    userName: "Jamie Lee",
    userAvatar: "/person-smiling-avatar.jpg",
    action: "is attending",
    timestamp: "2025-01-17T14:00:00Z",
  },
  {
    id: "fan4",
    eventId: "3",
    userName: "Morgan Chen",
    userAvatar: "/asian-person-avatar.jpg",
    action: "commented on a moment",
    timestamp: "2025-01-22T19:30:00Z",
  },
  {
    id: "jazz-fan-1",
    eventId: "jazz-1",
    userName: "David L.",
    userAvatar: "/jazz-fan-avatar-1.jpg",
    action: "posted a moment",
    timestamp: "2025-01-24T22:30:00Z",
  },
  {
    id: "jazz-fan-2",
    eventId: "jazz-1",
    userName: "Rachel S.",
    userAvatar: "/jazz-fan-avatar-2.jpg",
    action: "is attending",
    timestamp: "2025-01-24T18:00:00Z",
  },
  {
    id: "jazz-fan-3",
    eventId: "jazz-2",
    userName: "Michael R.",
    userAvatar: "/jazz-fan-avatar-3.jpg",
    action: "posted a moment",
    timestamp: "2025-01-25T21:45:00Z",
  },
  {
    id: "jazz-fan-5",
    eventId: "jazz-3",
    userName: "James W.",
    userAvatar: "/jazz-fan-avatar-5.jpg",
    action: "liked this event",
    timestamp: "2025-01-26T20:00:00Z",
  },
]
